# Generated by Django 4.2.4 on 2023-10-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
