# Generated by Django 4.2.4 on 2023-10-28 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('round_table', '0003_remove_replies_parent_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='books',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
            preserve_default=False,
        ),
    ]
