# Generated by Django 4.2.4 on 2023-10-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('round_table', '0004_forum_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='books',
            new_name='book',
        ),
    ]
