# Generated by Django 4.2.6 on 2023-10-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='buyed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='reviewed',
            field=models.IntegerField(default=0),
        ),
    ]
