# Generated by Django 4.2.6 on 2023-10-28 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_buyed_user_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='carts',
        ),
    ]
