# Generated by Django 4.2.6 on 2023-10-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_form_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='form_submitted',
        ),
    ]
