# Generated by Django 4.2.6 on 2023-10-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='readed',
            field=models.IntegerField(default=0),
        ),
    ]
