# Generated by Django 4.2.6 on 2023-12-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20231029_1516'),
        ('books', '0003_auto_20231029_2214'),
    ]

    operations = [
    ]
