# Generated by Django 4.2.6 on 2023-10-27 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('make_journey_jurnal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='buys',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='book',
            name='page_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='book',
            name='readed',
        ),
    ]
