# Generated by Django 4.2.6 on 2023-10-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_journey_jurnal', '0002_remove_book_buys_remove_book_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='lang',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
