# Generated by Django 4.2.6 on 2023-10-26 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20231026_1232'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.inventory')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
