# Generated by Django 4.2.6 on 2023-10-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_inventory_inventorybook_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='Inventory', max_length=100),
        ),
    ]
